[project]
name = "keycardai-mcp-fastmcp"
version = "0.1.0"
description = "FastMCP integration for KeyCard OAuth client with automated token exchange and authentication"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "KeyCard AI", email = "support@keycard.ai" }]
dependencies = [
    "pydantic>=2.11.7",
    "pydantic-settings>=2.7.1",
    "httpx>=0.27.2",
    "keycardai-oauth",
    "fastmcp>=2.12.0",
]
keywords = ["fastmcp", "mcp", "model-context-protocol", "oauth", "token-exchange", "authentication", "keycard"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Security",
    "Topic :: Internet :: WWW/HTTP :: Session",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/keycardai/python-sdk"
Repository = "https://github.com/keycardai/python-sdk"
Documentation = "https://docs.keycardai.com"
Issues = "https://github.com/keycardai/python-sdk/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/keycardai"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501",  # line too long, we'll handle case by case
]
isort = { combine-as-imports = true, known-first-party = ["keycardai"] }

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["T20"]

[tool.mypy]
strict = true
disallow_incomplete_defs = false
disallow_untyped_defs = false
disallow_untyped_calls = false

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

[tool.coverage.run]
source = ["tests", "src/keycardai"]

[tool.coverage.report]
show_missing = true
exclude_also = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "@abc.abstractmethod",
    "raise NotImplementedError",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra -q"

[tool.commitizen]
name = "cz_customize"
version = "0.0.0"
tag_format = "${version}-keycardai-mcp-fastmcp"
ignored_tag_formats = ["${version}-*"]
update_changelog_on_bump = true
bump_message = "bump: keycardai-mcp-fastmcp $current_version → $new_version"
major_version_zero = true

[tool.commitizen.customize]
changelog_pattern = "^(feat|fix|refactor|perf|test|build|ci|revert)\\(keycardai-mcp-fastmcp\\)(!)?:"
