[project]
name = "dynamic-client-registration"
version = "0.1.0"
description = "OAuth 2.0 Dynamic Client Registration demonstration with Keycard"
requires-python = ">=3.10"
dependencies = [
    "keycardai-oauth",
]

[tool.uv.sources]
keycardai-oauth = { path = "../../", editable = true }

[project.scripts]
dcr-demo = "main:main"
